import turtle

turtle.pensize(6)


def body():
    turtle.penup()
    turtle.goto(100, -75)
    turtle.pendown()
    turtle.color("black", "#71A398")
    turtle.begin_fill()
    turtle.setheading(93)
    turtle.forward(200)
    turtle.circle(85, 180)
    turtle.setheading(267)
    turtle.forward(200)
    turtle.setheading(273)
    turtle.circle(95, 180)
    turtle.end_fill()


def legs():
    turtle.penup()
    turtle.goto(-72.5, -135)
    turtle.pendown()
    turtle.color("black", "#71A398")
    turtle.begin_fill()
    turtle.setheading(210)
    turtle.circle(150, 25)
    turtle.setheading(235)
    turtle.circle(12.5, 140)
    turtle.setheading(18)
    turtle.circle(200, 23)
    turtle.setheading(127)
    turtle.circle(75, 33)
    turtle.end_fill()

    # leg2
    turtle.penup()
    turtle.goto(85, -132.5)
    turtle.pendown()
    turtle.color("black", "#71A398")
    turtle.begin_fill()
    turtle.setheading(330)
    turtle.circle(-150, 25)
    turtle.setheading(305)
    turtle.circle(-12.5, 140)
    turtle.setheading(162)
    turtle.circle(-200, 23)
    turtle.setheading(53)
    turtle.circle(-75, 33)
    turtle.end_fill()


def arms():
    turtle.penup()
    turtle.goto(-35, -167.5)
    turtle.pendown()
    turtle.color("black", "#71A398")
    turtle.begin_fill()
    turtle.setheading(115)
    turtle.circle(-135, 40)
    turtle.setheading(85)
    turtle.circle(-11.5, 165)
    turtle.setheading(285)
    turtle.circle(-222.5, 23.7)
    turtle.setheading(239)
    turtle.circle(-12, 105)
    turtle.end_fill()

    # arm2
    turtle.penup()
    turtle.goto(50, -167.5)
    turtle.pendown()
    turtle.color("black", "#71A398")
    turtle.begin_fill()
    turtle.setheading(65)
    turtle.circle(135, 40)
    turtle.setheading(95)
    turtle.circle(11.5, 165)
    turtle.setheading(255)
    turtle.circle(222.5, 23.7)
    turtle.setheading(301)
    turtle.circle(12, 105)
    turtle.end_fill()


def antennae():
    turtle.penup()
    turtle.goto(-20, 195)
    turtle.pendown()
    turtle.color("black", "#1B4B3B")
    turtle.begin_fill()
    turtle.setheading(100)
    turtle.circle(190, 75)
    turtle.setheading(345)
    turtle.circle(-210, 68)
    turtle.goto(-20, 195)
    turtle.end_fill()

    box = 40
    turtle.penup()
    turtle.goto(-60, 225)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(30)
    turtle.forward(box)
    turtle.setheading(120)
    turtle.forward(box - 30)
    turtle.setheading(210)
    turtle.forward(box)
    turtle.goto(-60, 225)
    turtle.end_fill()

    box = 35
    turtle.penup()
    turtle.goto(-90, 275)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(40)
    turtle.forward(box)
    turtle.setheading(130)
    turtle.forward(box - 25)
    turtle.setheading(220)
    turtle.forward(box)
    turtle.goto(-90, 275)
    turtle.end_fill()

    box = 30
    turtle.penup()
    turtle.goto(-120, 305)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(50)
    turtle.forward(box)
    turtle.setheading(140)
    turtle.forward(box - 22.5)
    turtle.setheading(230)
    turtle.forward(box)
    turtle.goto(-120, 305)
    turtle.end_fill()

    x = -150
    y = 325
    box = 25
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(60)
    turtle.forward(box)
    turtle.setheading(150)
    turtle.forward(box - 17.5)
    turtle.setheading(240)
    turtle.forward(box)
    turtle.goto(x, y)
    turtle.end_fill()

    # antenna2
    turtle.penup()
    turtle.goto(35, 195)
    turtle.pendown()
    turtle.color("black", "#1B4B3B")
    turtle.begin_fill()
    turtle.setheading(80)
    turtle.circle(-190, 75)
    turtle.setheading(195)
    turtle.circle(210, 68)
    turtle.goto(35, 195)
    turtle.end_fill()

    box = 40
    x2 = 45
    y2 = 250
    turtle.penup()
    turtle.goto(x2, y2)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(-30)
    turtle.forward(box)
    turtle.setheading(-120)
    turtle.forward(box - 30)
    turtle.setheading(-210)
    turtle.forward(box)
    turtle.goto(x2, y2)
    turtle.end_fill()

    box = 35
    x3 = 80
    y3 = 300
    turtle.penup()
    turtle.goto(x3, y3)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(-30)
    turtle.forward(box)
    turtle.setheading(-120)
    turtle.forward(box - 25)
    turtle.setheading(-210)
    turtle.forward(box)
    turtle.goto(x3, y3)
    turtle.end_fill()

    box = 30
    x4 = 115
    y4 = 335
    turtle.penup()
    turtle.goto(x4, y4)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(-40)
    turtle.forward(box)
    turtle.setheading(-130)
    turtle.forward(box - 22.5)
    turtle.setheading(-220)
    turtle.forward(box)
    turtle.goto(x4, y4)
    turtle.end_fill()

    box = 25
    x5 = 150
    y5 = 350
    turtle.penup()
    turtle.goto(x5, y5)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(-50)
    turtle.forward(box)
    turtle.setheading(-140)
    turtle.forward(box - 17.5)
    turtle.setheading(-230)
    turtle.forward(box)
    turtle.goto(x5, y5)
    turtle.end_fill()


def face():
    turtle.penup()
    turtle.goto(-60, 165)
    turtle.pendown()
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.setheading(45)
    turtle.circle(-92.5, 95)
    turtle.setheading(162)
    turtle.forward(14.5)
    turtle.setheading(315)
    turtle.forward(16.5)
    turtle.setheading(160)
    turtle.forward(14.5)
    turtle.setheading(305)
    turtle.forward(16.5)
    turtle.setheading(137)
    turtle.circle(92.5, 85)
    turtle.setheading(55)
    turtle.forward(14.5)
    turtle.setheading(200)
    turtle.forward(16.5)
    turtle.setheading(45)
    turtle.forward(14.5)
    turtle.setheading(200)
    turtle.forward(16.5)
    turtle.setheading(54)
    turtle.forward(14.5)
    turtle.end_fill()

    # eye
    turtle.penup()
    turtle.goto(50, 70)
    turtle.pendown()
    turtle.fillcolor("#FDED9F")
    turtle.begin_fill()
    turtle.setheading(65)
    turtle.circle(60, 90)
    turtle.circle(40, 60)
    turtle.circle(60, 90)
    turtle.setheading(308)
    turtle.circle(50, 120)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(22, 70)
    turtle.pendown()
    turtle.color("#FD4E39", "#FD4E39")
    turtle.begin_fill()
    turtle.setheading(46)
    for _ in range(2):
        turtle.circle(85 / 2, 90)
        turtle.circle(47.5 / 2, 90)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(-15, 95)
    turtle.pendown()
    turtle.color("white", "white")
    turtle.begin_fill()
    turtle.setheading(75)
    turtle.circle(-20, 145)
    turtle.setheading(300)
    turtle.circle(-5, 155)
    turtle.setheading(130)
    turtle.forward(5)
    turtle.setheading(103)
    turtle.circle(7.5, 150)
    turtle.setheading(225)
    turtle.forward(5)
    turtle.setheading(220)
    turtle.circle(-5, 155)
    turtle.end_fill()

    # mouth
    turtle.penup()
    turtle.goto(-43, 58.5)
    turtle.pendown()
    turtle.color("black")
    turtle.setheading(100)
    turtle.circle(17.5, -140)

    turtle.penup()
    turtle.goto(55, 58.5)
    turtle.pendown()
    turtle.setheading(80)
    turtle.circle(-17.5, -140)

    turtle.penup()
    turtle.goto(-48, 42.5)
    turtle.pendown()
    turtle.setheading(120)
    turtle.circle(-50, -60)
    turtle.setheading(0)
    turtle.forward(20)

    turtle.penup()
    turtle.goto(60, 42.5)
    turtle.pendown()
    turtle.setheading(60)
    turtle.circle(50, -60)


antennae()
body()
legs()
arms()
face()

turtle.hideturtle()
turtle.done()
